### ISSUE TITLE
Fix GitHub Pages Build

### ISSUE THREAD

**Issue by chrisdaaz** [alexandra-dp/LODproject#6]
Hi @alexandra-dp!

I think I see a similar problem you're experiencing with your GitHub Pages build as I saw in another student's final project repository. Take a look here: https://github.com/SusanAVanD/SusanAVanD.github.io/issues/3#issuecomment-1977940282

I think you essentially want to create a Markdown file that looks something similar to this: https://github.com/pages-themes/slate/blob/master/index.md

**Comment by alexandra-dp** [comment]
Hi @chrisdaaz 

Thanks for that, it has helped. I also noticed my _config.yml file had trailing spaces and that's what was preventing the site to be built... so there's some progress!

I'll continue playing around with this (for example, I was trying to make a version to run locally, I don't think that has worked but I'll check again).

Alexandra
